version: '3.3'

services:
  time-management-db:
    container_name: time-management-db
    image: postgres:14-alpine3.14
    restart: unless-stopped
    environment:
      POSTGRES_DB: tm-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - time-management-db:/var/opt/db
    networks:
      - time-management-network

volumes:
  time-management-db:
    driver: local

networks:
  time-management-network: